[2023-06-28T02:09:39.245+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T21:53:26-04:00 [queued]>
[2023-06-28T02:09:39.255+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T21:53:26-04:00 [queued]>
[2023-06-28T02:09:39.255+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T02:09:39.256+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-28T02:09:39.256+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-28T02:09:39.296+0000] {taskinstance.py:1309} INFO - Executing <Task(S3ToSqlOperator): transfer_s3_to_rds> on 2023-06-28 01:53:26+00:00
[2023-06-28T02:09:39.312+0000] {standard_task_runner.py:55} INFO - Started process 15283 to run task
[2023-06-28T02:09:39.319+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'transfer_s3_to_rds', 'manual__2023-06-27T21:53:26-04:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmp8uw4lhf5']
[2023-06-28T02:09:39.322+0000] {standard_task_runner.py:83} INFO - Job 202: Subtask transfer_s3_to_rds
[2023-06-28T02:09:39.455+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.transfer_s3_to_rds manual__2023-06-27T21:53:26-04:00 [running]> on host 8b415078c232
[2023-06-28T02:09:39.788+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=transfer_s3_to_rds
AIRFLOW_CTX_EXECUTION_DATE=2023-06-28T01:53:26+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T21:53:26-04:00
[2023-06-28T02:09:39.790+0000] {s3_to_sql.py:101} INFO - Loading pnadc_data_2023/processed/processed_data_pnadc_2023_06_28.csv to SQL table people_info...
[2023-06-28T02:09:39.815+0000] {base.py:73} INFO - Using connection ID 'aws_conn' for task execution.
[2023-06-28T02:09:39.815+0000] {connection_wrapper.py:337} INFO - AWS Connection (conn_id='aws_conn', conn_type='aws') credentials retrieved from login and password.
[2023-06-28T02:09:45.458+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-28T02:09:46.067+0000] {base.py:73} INFO - Using connection ID 'postgres_conn' for task execution.
[2023-06-28T03:28:02.166+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/transfers/s3_to_sql.py", line 117, in execute
    commit_every=self.commit_every,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 467, in insert_rows
    cur.execute(sql, values)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.

[2023-06-28T03:28:02.314+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=get_pnadc_data_new, task_id=transfer_s3_to_rds, execution_date=20230628T015326, start_date=20230628T020939, end_date=20230628T032802
[2023-06-28T03:28:02.672+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 202 for task transfer_s3_to_rds (server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
; 15283)
[2023-06-28T03:28:02.735+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-06-28T03:28:02.984+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
