[2023-06-27T07:17:39.204+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T03:17:32-04:00 [queued]>
[2023-06-27T07:17:39.215+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T03:17:32-04:00 [queued]>
[2023-06-27T07:17:39.215+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T07:17:39.215+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-06-27T07:17:39.215+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-06-27T07:17:39.321+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_mongodb_data> on 2023-06-27 07:17:32+00:00
[2023-06-27T07:17:39.331+0000] {standard_task_runner.py:55} INFO - Started process 2295 to run task
[2023-06-27T07:17:39.337+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_pnadc_data_new', 'get_mongodb_data', 'manual__2023-06-27T03:17:32-04:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/get_pnadc_data_new.py', '--cfg-path', '/tmp/tmpmq64b_6y']
[2023-06-27T07:17:39.340+0000] {standard_task_runner.py:83} INFO - Job 6: Subtask get_mongodb_data
[2023-06-27T07:17:39.522+0000] {task_command.py:389} INFO - Running <TaskInstance: get_pnadc_data_new.get_mongodb_data manual__2023-06-27T03:17:32-04:00 [running]> on host 33a038a7552c
[2023-06-27T07:17:39.702+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_pnadc_data_new
AIRFLOW_CTX_TASK_ID=get_mongodb_data
AIRFLOW_CTX_EXECUTION_DATE=2023-06-27T07:17:32+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-06-27T03:17:32-04:00
[2023-06-27T07:17:39.714+0000] {base.py:73} INFO - Using connection ID 'mongodb_conn' for task execution.
[2023-06-27T07:31:26.179+0000] {local_task_job.py:277} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2023-06-27T07:31:26.208+0000] {process_utils.py:133} INFO - Sending Signals.SIGTERM to group 2295. PIDs of all processes in the group: [2295]
[2023-06-27T07:31:26.209+0000] {process_utils.py:84} INFO - Sending the signal Signals.SIGTERM to group 2295
[2023-06-27T07:31:26.209+0000] {taskinstance.py:1488} ERROR - Received SIGTERM. Terminating subprocesses.
[2023-06-27T07:31:28.464+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=2295, status='terminated', exitcode=0, started='07:17:39') (2295) terminated with exit code 0
